# Generated by Django 3.0.5 on 2020-04-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(max_length=30)),
                ('FirstPlaceTitle', models.CharField(max_length=30)),
                ('FirstPlaceDescription', models.TextField(max_length=150)),
                ('SecondPlaceTitle', models.CharField(max_length=30)),
                ('SecondPlaceDescription', models.TextField(max_length=150)),
                ('ThirdlaceTitle', models.CharField(max_length=30)),
                ('ThirdPlaceDescription', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartupName', models.CharField(max_length=100)),
                ('TitleDescription', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=300)),
                ('Main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Main')),
            ],
        ),
    ]
