# Generated by Django 3.0.5 on 2020-04-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Email', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(default='Template 1', max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, max_length=200)),
                ('ButtonText', models.CharField(max_length=100)),
                ('ButtonLink', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(default='Template 1', max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=300)),
                ('ButtonText', models.CharField(max_length=20)),
                ('ButtonLink', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImagesName', models.CharField(max_length=50)),
                ('category1', models.CharField(blank=True, max_length=50)),
                ('title1', models.TextField(blank=True, max_length=100)),
                ('category2', models.CharField(blank=True, max_length=50)),
                ('title2', models.TextField(blank=True, max_length=100)),
                ('category3', models.CharField(blank=True, max_length=50)),
                ('title3', models.TextField(blank=True, max_length=100)),
                ('category4', models.CharField(blank=True, max_length=50)),
                ('title4', models.TextField(blank=True, max_length=100)),
                ('category5', models.CharField(blank=True, max_length=50)),
                ('title5', models.TextField(blank=True, max_length=100)),
                ('category6', models.CharField(blank=True, max_length=50)),
                ('title6', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartupName', models.CharField(max_length=100)),
                ('FirstSession', models.CharField(max_length=20)),
                ('SecondSession', models.CharField(max_length=20)),
                ('ThirdSession', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(default='Template 1', max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=300)),
                ('ButtonText', models.CharField(max_length=20)),
                ('ButtonLink', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(default='Template 1', max_length=50)),
                ('FirstItemTitle', models.CharField(max_length=100)),
                ('FirstItemDescription', models.TextField(max_length=300)),
                ('SecondItemTitle', models.CharField(max_length=100)),
                ('SecondItemDescription', models.TextField(max_length=300)),
                ('ThirdItemTitle', models.CharField(max_length=100)),
                ('ThirdItemDescription', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.AddField(
            model_name='all',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contact', verbose_name='Contact session'),
        ),
        migrations.AddField(
            model_name='all',
            name='download',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DownloadSession', verbose_name='Download session'),
        ),
        migrations.AddField(
            model_name='all',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Images', verbose_name='Chose an images description'),
        ),
        migrations.AddField(
            model_name='all',
            name='navigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Navigation', verbose_name='Chose a navigation'),
        ),
        migrations.AddField(
            model_name='all',
            name='session1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.First', verbose_name='Chose a session 1'),
        ),
        migrations.AddField(
            model_name='all',
            name='session2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Second', verbose_name='Chose a session 2'),
        ),
        migrations.AddField(
            model_name='all',
            name='session3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Third', verbose_name='Chose a session 3'),
        ),
    ]
