# Generated by Django 3.0.5 on 2020-04-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200402_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='FourthSession',
            field=models.CharField(default='Contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='FirstSession',
            field=models.CharField(default='About', max_length=20),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='SecondSession',
            field=models.CharField(default='Services', max_length=20),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='ThirdSession',
            field=models.CharField(default='Portifolio', max_length=20),
        ),
    ]
