# Generated by Django 3.0.5 on 2020-04-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200402_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='third',
            name='FourthItemDescription',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='third',
            name='FourthItemTitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
