# Generated by Django 3.0.5 on 2020-04-02 22:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0005_auto_20200402_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Second',
            new_name='AboutYou',
        ),
        migrations.RenameModel(
            old_name='First',
            new_name='FirstPlace',
        ),
        migrations.RenameModel(
            old_name='Third',
            new_name='YourService',
        ),
    ]
